import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createChinesePresentation} from '../payload/openclaw/dist/openclaw-acp-reasoning-presentation-v38.mjs';
async function fixture({long=false,fail=false,failEdits=false}={}){
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ocx-cn-test-'));await fs.mkdir(path.join(dir,'bin'));
 await fs.writeFile(path.join(dir,'bin/openclaw-acp-reasoning-cn.mjs'),fail?'export async function finalizeReasoningChinese(){throw Error("translation failed")}':`export async function finalizeReasoningChinese(){return {summaryZh:'中文摘要',fullZh:${JSON.stringify('中文正文。'.repeat(long?1300:10))}}}`);
 const edited=[],deleted=[],docs=[],order=[];
 const presentation=createChinesePresentation({telegramDeps:{},deliveryBaseOptions:{},bot:{api:{deleteMessage:async(_,id)=>{deleted.push(id);order.push('delete');return true;}}},chatId:1,cfg:{},route:{accountId:'test'},editMessageTelegram:async(_,id,text)=>{if(failEdits)throw Error('edit');edited.push({id,text});order.push('edit');},mediaLocalRoots:[dir],resolveStateDir:()=>dir,logVerbose(){},formatErrorMessage:String,deliverReplies:async options=>{docs.push(await fs.readFile(options.replies[0].mediaUrl,'utf8'));order.push('document');return {delivered:true}}});
 return {presentation,edited,deleted,docs,order,cleanup:()=>fs.rm(dir,{recursive:true})};
}
for(const long of [false,true])test(`copied v3.8 ${long?'attachment':'inline'} presentation commits before deleting secondary messages`,async()=>{const f=await fixture({long});try{await f.presentation.start({sourceText:'Synthetic public test.',primaryMessageId:1,messageIds:[1,2,3],canonicalMessageCount:3,traceMode:'test'});assert.match(f.edited[0].text,/blockquote expandable/);assert.deepEqual(f.deleted,[2,3]);assert.equal(f.docs.length,long?1:0);assert.ok(f.order.indexOf('edit')<f.order.indexOf('delete'));if(long)assert.ok(f.order.indexOf('document')<f.order.indexOf('edit'));}finally{await f.cleanup();}});
test('translator failure commits failure notice before cleanup; unconfirmed notice preserves originals',async()=>{for(const failEdits of [false,true]){const f=await fixture({fail:true,failEdits});try{await f.presentation.start({sourceText:'Synthetic public test.',primaryMessageId:1,messageIds:[1,2],canonicalMessageCount:2,traceMode:'test'});assert.equal(f.deleted.length,failEdits?0:1);if(!failEdits)assert.match(f.edited[0].text,/整理失败/);}finally{await f.cleanup();}}});
